<a href="https://colab.research.google.com/github/sachinchoudhary12321/Pytorch/blob/main/basic_of_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
if torch.cuda.is_available():
    print(f"cuda is available {torch.cuda.get_device_name(0)}")
else:
    print("cuda is not available")

cuda is not available


create **tensor**

In [ ]:
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.5752, 0.4787, 0.5782],
        [0.7536, 0.1093, 0.4771]])

In [ ]:
torch.rand(2,3)

tensor([[0.1076, 0.9829, 0.1483],
        [0.5956, 0.3634, 0.7842]])

In [ ]:
# rand value is fix use for reproducibility
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
torch.tensor([[1,2,3],[12,35,5]])

tensor([[ 1,  2,  3],
        [12, 35,  5]])

In [ ]:
print(torch.arange(0,10,2))
print(torch.linspace(0,10,20
                     ))
print(torch.eye(5))
print(torch.full((3,4),4))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])


**how to get the shape**

In [ ]:
x = torch.ones(2,5)
print(x)
print(x.shape)
print(x.size())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([2, 5])
torch.Size([2, 5])


In [ ]:
torch.empty_like(x)

tensor([[5.6788e+29, 4.3935e-41, 2.8716e-30, 0.0000e+00, 4.4842e-44],
        [0.0000e+00, 1.1210e-43, 0.0000e+00, 2.9047e-30, 0.0000e+00]])

In [ ]:
a = torch.tensor([[1,2,4], [2,3,5]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.rand_like(x)

tensor([[0.6938, 0.9693, 0.6178, 0.3304, 0.5479],
        [0.4440, 0.7041, 0.5573, 0.6959, 0.9849]])

** how to get the data type **

In [ ]:
x.type()

'torch.FloatTensor'

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype = torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
x.to(torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [ ]:
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


**mathamatiacal operation**

In [ ]:
x = torch.rand(2,2)

In [ ]:
print(x)

tensor([[0.2924, 0.4823],
        [0.6150, 0.4967]])


In [ ]:
x=x**2
print(x)

tensor([[0.0855, 0.2326],
        [0.3782, 0.2467]])


In [ ]:
# perform the element wise
y = torch.ones(2,2)
print(y)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(x**y)

tensor([[0.0855, 0.2326],
        [0.3782, 0.2467]])


In [ ]:
a = x - 100

In [ ]:
(a)

tensor([[-99.9145, -99.7674],
        [-99.6218, -99.7533]])

In [ ]:
torch.neg(y)

tensor([[-1., -1.],
        [-1., -1.]])

In [ ]:
b = torch.tensor([[1,2,4],[2,3,5]],dtype=int)

In [ ]:
torch.clamp(b,min=2,max=3)

tensor([[2, 2, 3],
        [2, 3, 3]])

In [ ]:
#reduction operation
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
print(e)

tensor([[8., 9., 2.],
        [0., 9., 9.]])


In [ ]:
torch.sum(e)

tensor(37.)

In [ ]:
torch.sum(e,dim=1)#dim=0 column,1 = row

tensor([19., 18.])

In [ ]:
torch.tensor([13,10,7])

tensor([13, 10,  7])

In [ ]:
torch.mean(e)# it only work on the dtype is long long

tensor(6.1667)

In [ ]:
torch.var(e,dim=0)

tensor([32.0000,  0.0000, 24.5000])

In [ ]:
torch.argmax(e,dim=1)

tensor([1, 1])

In [ ]:
print(e)

tensor([[8., 9., 2.],
        [0., 9., 9.]])


In [ ]:
print(torch.matmul(x,y))

tensor([[0.3181, 0.3181],
        [0.6250, 0.6250]])


In [ ]:
#inplace operation
n = torch.rand(size=(2,3),dtype=torch.float32)
m = torch.rand(size=(2,3),dtype=torch.float32)

In [ ]:
n

tensor([[0.1212, 0.0490, 0.0310],
        [0.7192, 0.8067, 0.8379]])

In [ ]:
m.add_(n)

tensor([[0.8906, 0.7185, 0.7512],
        [0.9427, 1.7569, 1.3034]])

In [ ]:
m.softmax(dim=1)

tensor([[0.3688, 0.3104, 0.3208],
        [0.2131, 0.4811, 0.3057]])

In [ ]:
#copy the tensor
b = m

In [ ]:
id(b)

134660924361296

In [ ]:
id(b)

134660924361296

In [ ]:
b = a.clone()

In [ ]:
id(a)

134660934932016

In [ ]:
id(b)

134660934963264

In [ ]:
a[0][0]=100

In [ ]:
id(a)

134660934932016

In [ ]:
a

tensor([[100.0000, -99.7674],
        [-99.6218, -99.7533]])

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = torch.device('cuda')

In [ ]:
device

device(type='cuda')

In [ ]:
torch.rand((2,3),device=device
           )

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5752, 0.4787, 0.5782],
        [0.7536, 0.1093, 0.4771]])

In [ ]:
b = a.to(device)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
b

tensor([[-99.9145, -99.7674],
        [-99.6218, -99.7533]])

In [ ]:
b+9

tensor([[-90.9145, -90.7674],
        [-90.6218, -90.7533]])

In [ ]:
torch.tensor(3.0)

tensor(3.)

**AUTO GRADE**

In [ ]:
import torch


In [ ]:
x = torch.tensor(3.0,requires_grad=True)

In [ ]:
y = x**2

In [ ]:
print(x)

tensor(3., requires_grad=True)


In [ ]:
print(y)

tensor(9., grad_fn=<PowBackward0>)


In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
x = torch.tensor(3.0,requires_grad=True)

In [ ]:
y = x**2

In [ ]:
import math

In [ ]:
z = torch.sin(y)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

In [ ]:
y.grad

/tmp/ipykernel_491/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  y.grad


In [ ]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [ ]:
def loss(prediction, target):
    """Binary cross entropy loss function with clipping for stability."""
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -target * torch.log(prediction) - (1 - target) * torch.log(1 - prediction)

In [ ]:
z = w * x + b
y_pred = torch.sigmoid(z)

# Changed variable name from 'loss' to 'first_loss_val' to prevent overwriting the function
first_loss_val = loss(y_pred, y)
print(first_loss_val)

tensor(6.7012, grad_fn=<SubBackward0>)


In [ ]:
loss

<function __main__.loss(prediction, target)>

In [ ]:
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

dy_pred_dz = y_pred*(1-y_pred)

dz_dw = x

dz_db = 1

dl_dw = dloss_dy_pred*dy_pred_dz*dz_dw

dl_db = dloss_dy_pred*dy_pred_dz*dz_db

In [ ]:
print(dl_dw)
print(dl_db)

tensor(6.6918, grad_fn=<MulBackward0>)
tensor(0.9988, grad_fn=<MulBackward0>)


In [ ]:
x = torch.tensor(6.7)
y=torch.tensor(0.0)



In [ ]:
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z = w*x + b

In [ ]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
# Use a unique name for the result to avoid overwriting the 'loss' function
loss_val = loss(y_pred, y)
loss_val

tensor(6.7012, grad_fn=<SubBackward0>)

In [ ]:
loss_val.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

In [ ]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
y= (x**2).mean()

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

# clear grad

In [ ]:
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x**2

In [ ]:
y.backward()# this wiil change by the upfdate it solve the problem of theclear grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
x.grad

tensor(0.)

In [ ]:
x.grad.zero_()

tensor(0.)

In [ ]:
x.requires_grad_(False)

tensor(2.)

In [ ]:
x

tensor(2.)

In [ ]:
y = x**2

In [ ]:
y

tensor(4.)

In [ ]:
y.backward()# becoz grad function is not avilable

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
# detach
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
z = x.detach()# remove the required grad
z

tensor(2.)

In [ ]:
y = x**2

In [ ]:
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y1 = z**2
y1

tensor(4.)

In [ ]:
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
with torch.no_grad():
  y = x**2


In [ ]:
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()