<a href="https://colab.research.google.com/github/sachinchoudhary12321/Pytorch/blob/main/use_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import pandas as pd


In [ ]:
class Model(nn.Module):
  def __init__(self, nums_feature):
    super().__init__()
    self.linear = nn.Linear(nums_feature, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, feature):
    out = self.linear(feature)
    out = self.sigmoid(out)
    return out








In [ ]:
feature = torch.rand(10,5)

model = Model(feature.shape[1])


model(feature)



tensor([[0.3716],
        [0.5017],
        [0.3644],
        [0.4919],
        [0.4565],
        [0.3925],
        [0.3944],
        [0.3559],
        [0.3914],
        [0.4327]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.4259], requires_grad=True)

In [ ]:
import sys
!{sys.executable} -m pip install torchinfo
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Hidden layer


In [ ]:
class Model(nn.Module):
  def __init__(self, nums_feature):
    super().__init__()
    # it is the first layer which is take the 5 input and output is 3
    self.linear1 = nn.Linear(nums_feature, 3)

    self.relu = nn.ReLU()
# hidden layer ip=3,op=1
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, feature):
    out = self.linear1(feature)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [ ]:
feature = torch.rand(10,5)

model = Model(feature.shape[1])


model(feature)

tensor([[0.5790],
        [0.5902],
        [0.5880],
        [0.5931],
        [0.5952],
        [0.5820],
        [0.6009],
        [0.6209],
        [0.5985],
        [0.5873]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2590,  0.4364, -0.3100,  0.3034, -0.0482],
        [ 0.1423,  0.0637,  0.2651, -0.4073, -0.2653],
        [-0.2960,  0.2837, -0.3346, -0.0400, -0.1694]], requires_grad=True)

In [ ]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

# sequential container

In [ ]:
class Model(nn.Module):
  def __init__(self, nums_feature):
    super().__init__()

    self.network = nn.Sequential(
    nn.Linear(nums_feature, 3),
    nn.ReLU(),
# hidden layer ip=3,op=1
    nn.Linear(3, 1),
    nn.Sigmoid(),
    )
    # it is the first layer which is take the 5 input and output is 3


  def forward(self, feature):
    out = self.network(feature)
    return out

In [ ]:
feature = torch.rand(10,5)

model = Model(feature.shape[1])


model(feature)

tensor([[0.5739],
        [0.5579],
        [0.6015],
        [0.6432],
        [0.6030],
        [0.5798],
        [0.6154],
        [0.5485],
        [0.5738],
        [0.5013]], grad_fn=<SigmoidBackward0>)

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace = True)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
X_train_tensor = torch.tensor(X_train,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.float32)

In [ ]:
class MYSimpleNN(nn.Module):
  def __init__(self, nums_feature):
    super().__init__()

    self.network = nn.Sequential(
    nn.Linear(nums_feature, 3),
    nn.ReLU(),
# hidden layer ip=3,op=1
    nn.Linear(3, 1),
    nn.Sigmoid(),
    )
    # it is the first layer which is take the 5 input and output is 3


  def forward(self, feature):
    out = self.network(feature)
    return out

  def loss(self,y_pred,y_true):
    return torch.mean((y_pred-y_true)**2)


In [ ]:
learning_rate = 0.1
epochs = 20
model = MYSimpleNN(X_train_tensor.shape[1])
model = model.to(torch.float64) # Add this line to cast the model to float64

for epoch in range(epochs):
  model.zero_grad() # Zero the gradients before each epoch
  #forward
  # Cast X_train_tensor to float64 to match model.weights and model.bias dtype
  y_pred = model(X_train_tensor.to(torch.float64))
  loss = model.loss(y_pred,y_train_tensor.to(torch.float64))
  print(f'epoch{epoch}:loss{loss}')
  #backward
  loss.backward()

  with torch.no_grad():
    for param in model.parameters():
      if param.grad is not None:
        param -= learning_rate * param.grad


with torch.no_grad():
  y_pred = model.forward(X_test_tensor.to(torch.float64))
  y_pred = (y_pred>0.5).float()
  y_pred = y_pred.numpy()


epoch0:loss0.289918171292263
epoch1:loss0.28685315967295716
epoch2:loss0.2838568600289205
epoch3:loss0.28093794069477457
epoch4:loss0.2781280680625429
epoch5:loss0.2754322064448704
epoch6:loss0.2728709337963369
epoch7:loss0.27042051214952945
epoch8:loss0.26810024012230743
epoch9:loss0.26593753448514607
epoch10:loss0.26391902185301974
epoch11:loss0.26205498969195457
epoch12:loss0.26034847058803734
epoch13:loss0.25878333948644305
epoch14:loss0.2573489193823346
epoch15:loss0.2560315690682401
epoch16:loss0.2548261309803179
epoch17:loss0.25372113000632446
epoch18:loss0.25270392632601785
epoch19:loss0.25176712848378296


# loss function

In [ ]:
class MYSimpleNN(nn.Module):
  def __init__(self, nums_feature):
    super().__init__()

    self.network = nn.Sequential(
    nn.Linear(nums_feature, 3),
    nn.ReLU(),
# hidden layer ip=3,op=1
    nn.Linear(3, 1),
    nn.Sigmoid(),
    )
    # it is the first layer which is take the 5 input and output is 3


  def forward(self, feature):
    out = self.network(feature)
    return out



In [ ]:
loss_fn = nn.BCELoss()

In [ ]:
learning_rate = 0.1
epochs = 20
model = MYSimpleNN(X_train_tensor.shape[1])
model = model.to(torch.float64) # Add this line to cast the model to float64

for epoch in range(epochs):
  model.zero_grad() # Zero the gradients before each epoch
  #forward
  # Cast X_train_tensor to float64 to match model.weights and model.bias dtype
  y_pred = model(X_train_tensor.to(torch.float64))
  loss = loss_fn(y_pred,y_train_tensor.to(torch.float64).unsqueeze(1)) # Reshape y_train_tensor
  print(f'epoch{epoch}:loss{loss}')
  #backward
  loss.backward()

  with torch.no_grad():
    for param in model.parameters():
      if param.grad is not None:
        param -= learning_rate * param.grad


with torch.no_grad():
  y_pred = model.forward(X_test_tensor.to(torch.float64))
  y_pred = (y_pred>0.5).float()
  y_pred = y_pred.numpy()

epoch0:loss0.7888495436592686
epoch1:loss0.7802755788411726
epoch2:loss0.771797582136618
epoch3:loss0.7633576874230181
epoch4:loss0.754947705026661
epoch5:loss0.7465388564446319
epoch6:loss0.7382011281986449
epoch7:loss0.7299257508517015
epoch8:loss0.7216247923706116
epoch9:loss0.7132567812752456
epoch10:loss0.7047743716335827
epoch11:loss0.6961097739741132
epoch12:loss0.68722226440487
epoch13:loss0.6780629564317671
epoch14:loss0.6685369577196357
epoch15:loss0.6586157567367745
epoch16:loss0.6483680348219502
epoch17:loss0.6377583558937581
epoch18:loss0.6267364810815587
epoch19:loss0.6152767001088006


# torch optim

In [ ]:
learning_rate = 0.1
epochs = 20
model = MYSimpleNN(X_train_tensor.shape[1])
model = model.to(torch.float64) # Add this line to cast the model to float64

optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

for epoch in range(epochs):
  model.zero_grad() # Zero the gradients before each epoch
  #forward
  # Cast X_train_tensor to float64 to match model.weights and model.bias dtype
  y_pred = model(X_train_tensor.to(torch.float64))
  loss = loss_fn(y_pred,y_train_tensor.to(torch.float64).unsqueeze(1)) # Reshape y_train_tensor
  print(f'epoch{epoch}:loss{loss}')
  #backward
  optimizer.zero_grad()

  loss.backward()

  optimizer.step()



epoch0:loss0.6588893884106568
epoch1:loss0.6468913001281854
epoch2:loss0.6348973911773128
epoch3:loss0.6228277186616966
epoch4:loss0.6104079391276137
epoch5:loss0.5975413494115974
epoch6:loss0.5842265264678325
epoch7:loss0.5704088101883109
epoch8:loss0.5560553866841867
epoch9:loss0.5412183224159784
epoch10:loss0.5259580013846226
epoch11:loss0.510279352894361
epoch12:loss0.49427796998407
epoch13:loss0.4779845046826348
epoch14:loss0.46159753754380256
epoch15:loss0.4452419992728107
epoch16:loss0.4290973394567411
epoch17:loss0.41322522017169344
epoch18:loss0.39778351427427644
epoch19:loss0.38287004585657963


# mini batch gradient descent

In [ ]:
batch_size = 100
epochs = 20
n_samples = len(X_train_tensor)

for epoch in range(epochs):

  for start_idx in range(0,n_samples,batch_size):

    end_idx = start_idx + batch_size;
    X_batch = X_train_tensor[start_idx:end_idx]
    y_batch = y_train_tensor[start_idx:end_idx]

    # Zero the gradients before each epoch
  #forward
  # Cast X_train_tensor to float64 to match model.weights and model.bias dtype
    y_pred = model(X_batch.to(torch.float64))
    loss = loss_fn(y_pred,y_batch.to(torch.float64).unsqueeze(1)) # Reshape y_train_tensor
    print(f'epoch{epoch}:loss{loss}')
    #backward
    optimizer.zero_grad()

    loss.backward()

    optimizer.step()



epoch0:loss0.355531750999058
epoch0:loss0.3700482536254217
epoch0:loss0.3348569140718354
epoch0:loss0.34345934845947695
epoch0:loss0.3046948186788141
epoch1:loss0.2936288546236055
epoch1:loss0.31306553985292274
epoch1:loss0.2752180867039203
epoch1:loss0.29266096328091457
epoch1:loss0.25624164045899056
epoch2:loss0.24798325004906246
epoch2:loss0.270003468656645
epoch2:loss0.23049330070723018
epoch2:loss0.25562760012742614
epoch2:loss0.2213045590888676
epoch3:loss0.21456035814202207
epoch3:loss0.23804217832884464
epoch3:loss0.19737187102140868
epoch3:loss0.22848399827847474
epoch3:loss0.19574144973618396
epoch4:loss0.1901750869766672
epoch4:loss0.2139683969573494
epoch4:loss0.17257500588447733
epoch4:loss0.20776367616433458
epoch4:loss0.17667187686200037
epoch5:loss0.1711489766444307
epoch5:loss0.19527769578262014
epoch5:loss0.15216065835622988
epoch5:loss0.19190677135084308
epoch5:loss0.1620584265357178
epoch6:loss0.15564774934334058
epoch6:loss0.18043106257140262
epoch6:loss0.135364911

This code snippet demonstrates a training loop for a neural network using mini-batch gradient descent. Let's break it down:

### 1. Initialization

In [ ]:
batch_size = 100
epochs = 20
n_samples = len(X_train_tensor)


- **`batch_size = 100`**: Defines how many samples from the training data will be processed at once in each iteration of the inner loop. Using batches helps in faster training and more stable gradient updates.
- **`epochs = 20`**: Specifies the number of times the entire training dataset will be passed forward and backward through the neural network. One epoch means the model has seen the entire training dataset once.
- **`n_samples = len(X_train_tensor)`**: Gets the total number of samples in your training dataset (`X_train_tensor`). This is used to determine the range for iterating through batches.

### 2. Training Loop Structure

In [ ]:
for epoch in range(epochs):

  for start_idx in range(0,n_samples,batch_size):

    end_idx = start_idx + batch_size;
    X_batch = X_train_tensor[start_idx:end_idx]
    y_batch = y_train_tensor[start_idx:end_idx]

- **`for epoch in range(epochs):`**: This is the outer loop, which iterates `epochs` number of times. In each epoch, the model processes the entire training dataset.
- **`for start_idx in range(0,n_samples,batch_size):`**: This is the inner loop. It iterates through the training data in steps of `batch_size`.
  - `start_idx` marks the beginning index of the current batch.
  - `end_idx = start_idx + batch_size` marks the end index of the current batch.
  - `X_batch` and `y_batch` are created by slicing `X_train_tensor` and `y_train_tensor` to get the current mini-batch of features and labels, respectively.

### 3. Forward Pass and Loss Calculation

In [ ]:
    y_pred = model(X_batch.to(torch.float64))
    loss = loss_fn(y_pred,y_batch.to(torch.float64).unsqueeze(1)) # Reshape y_train_tensor
    print(f'epoch{epoch}:loss{loss}')

epoch19:loss0.05297549971307466


- **`y_pred = model(X_batch.to(torch.float64))`**: This performs the **forward pass**. The `X_batch` (input features for the current batch) is passed through the `model`. `.to(torch.float64)` ensures that the input data type matches the model's expected data type (which was cast to `float64` earlier in the notebook).
- **`loss = loss_fn(y_pred,y_batch.to(torch.float64).unsqueeze(1))`**: This calculates the **loss**. The `loss_fn` (Binary Cross-Entropy Loss, `nn.BCELoss()`, as defined in a previous cell) compares the model's predictions (`y_pred`) with the actual labels (`y_batch`).
  - `.unsqueeze(1)` is used to reshape `y_batch` to have a dimension of `[batch_size, 1]`, matching the output shape of `y_pred` from the model's final `nn.Linear` layer.
- **`print(f'epoch{epoch}:loss{loss}')`**: Prints the current epoch number and the calculated loss for the current batch.

### 4. Backward Pass and Optimization

In [ ]:
    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

- **`optimizer.zero_grad()`**: Before calculating gradients for the current batch, it's crucial to zero out any previously accumulated gradients. This prevents gradients from previous batches or iterations from interfering with the current update.
- **`loss.backward()`**: This performs the **backward pass** (backpropagation). It computes the gradients of the `loss` with respect to all trainable parameters in the model. These gradients indicate how much each parameter should be adjusted to reduce the loss.
- **`optimizer.step()`**: This updates the model's parameters using the calculated gradients. The `optimizer` (Stochastic Gradient Descent, `torch.optim.SGD`, as defined in a previous cell) applies the updates based on its configured learning rate to move the parameters in the direction that minimizes the loss.

In summary, this code iteratively feeds mini-batches of data to the neural network, calculates the prediction error, and then adjusts the network's weights and biases to minimize that error over multiple epochs.

In [ ]:
batch_size = 100
epochs = 20
n_samples = len(X_train_tensor)

for epoch in range(epochs):

  for start_idx in range(0,n_samples,batch_size):

    end_idx = start_idx + batch_size;
    X_batch = X_train_tensor[start_idx:end_idx]
    y_batch = y_train_tensor[start_idx:end_idx]

    # Zero the gradients before each epoch
  #forward
  # Cast X_train_tensor to float64 to match model.weights and model.bias dtype
    y_pred = model(X_batch.to(torch.float64))
    loss = loss_fn(y_pred,y_batch.to(torch.float64).unsqueeze(1)) # Reshape y_train_tensor
    print(f'epoch{epoch}:loss{loss}')
    #backward
    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

epoch0:loss0.04299555206965288
epoch0:loss0.09812068719991324
epoch0:loss0.028540642853694592
epoch0:loss0.08698760174070973
epoch0:loss0.06591815597919672
epoch1:loss0.04224750479364034
epoch1:loss0.0977001287459281
epoch1:loss0.028010405488967282
epoch1:loss0.08635005415636308
epoch1:loss0.06507426960463791
epoch2:loss0.04152737163197875
epoch2:loss0.09729470648507928
epoch2:loss0.027509199838133106
epoch2:loss0.08578424791581986
epoch2:loss0.06420071815472489
epoch3:loss0.040879618391482436
epoch3:loss0.09693979177790463
epoch3:loss0.02704378278614801
epoch3:loss0.08527851775095499
epoch3:loss0.06340812191525742
epoch4:loss0.040230651245041694
epoch4:loss0.0966056962079097
epoch4:loss0.026582747646598594
epoch4:loss0.08483328556542835
epoch4:loss0.06263497578549529
epoch5:loss0.039605211522205114
epoch5:loss0.09628101183766719
epoch5:loss0.026146367563541353
epoch5:loss0.08440083708518092
epoch5:loss0.06188955408659641
epoch6:loss0.03900199381780242
epoch6:loss0.09596498062249947
ep